sudo: false

language: python
python:
  - '3.4'
services:
  - mongodb
addons:
  hosts:
    - web
    - backend
    - frontend
    - database
env:
  global:
    - PYTHONPATH=$(pwd):$PYTHONPATH
install:
  - pip install -r sbcatalog/requirements/dev.txt

before_script:
  - sbcatalog/run.py &

script:
  - cd sbcatalog/tests && py.test && cd -
  - cd test/integration && py.test && cd -

after_script:
  - killall run.py
