sudo: false

language: python
python:
  - '3.4'
services:
  - mongodb
addons:
  hosts:
    - proxy
    - back
    - front
    - db
env:
  global:
    - PYTHONPATH=$(pwd):$PYTHONPATH
install:
  - pip install -r api/requirements/dev.txt

before_script:
  - api/run.py &

script:
  - py.test api/tests
  - cd test/integration && py.test && cd -

after_script:
  - killall run.py
