test:
  build: ./test
  volumes_from:
    - back
  links:
    - proxy
    - db

proxy:
  image: kobe25/sbcatalog-proxy:latest
  volumes:
    - ./proxy:/etc/nginx/conf.d:ro
  ports:
    - '127.0.0.1:8080:80'
  links:
    - front
    - back

front:
  image: kobe25/sbcatalog-front:latest
  volumes:
    - ./ui:/code:ro

back:
  image: kobe25/sbcatalog-back:latest
  volumes:
    - ./api:/code/api:ro
  links:
    - db

db:
  image: mongo:2.4
